Cargo.toml
Dockerfile
README.md
install-golang.sh
src/main.rs

The current `Dockerfile` in `main` does not work on host machines running `amd` architectures (it would only work if the `Dockerfile` is used on MacOS, not Linux).
With these updates, it should work no matter what the host machine is, it should be OS and architecture agnostic.
The main issue was the Go binary, since it requires a different binary for different operating systems and architectures.
Has been tested on MacOS and Debian.

refactor: improve Dockerfile

---

src/lib.rs
src/main.rs

- Updated the test urls
- Follow the new Graphcast-sdk namespace
Follow up to graphops/graphcast-sdk#85

refactor: new graphcast registry link, rename graphcast vars

---

.github/dependabot.yml
.versionrc.json
Cargo.toml
README.md
src/graphql/mod.rs
src/graphql/query_block_hash_from_number.graphql
src/graphql/query_indexing_statuses.graphql
src/graphql/schema_graph_node.graphql
src/graphql/schema_proof_of_indexing.graphql
src/lib.rs
src/main.rs

Reorder POI generation query
- Add `indexingStatuses` query to the graph node for the `network`.
- Based on the network returned, select the block provider provided by the user (`provider_endpoints`) to query for latest block number. This could be queried from the graph node directly but we are using the providers for deterministic send_message block consensus.
- Based on the network returned, select the block examination frequency in networks supported by the radio (`SUPPORTED_NETWORK_BLOCK_INTERVALS`).
- Query block hash from the graph node, with block provider as a fallback if failed (`blockHashFromNumber`).
- Query POI with network specific block number and block hash.
For the feature to work completely, I think we still need 
- Network specific `compare_block` instead of just one …

subgraph indexing network specific POI query

---

Cargo.toml
src/graphql/mod.rs
src/graphql/query_indexing_statuses.graphql
src/graphql/schema_graph_node.graphql
src/lib.rs
src/main.rs

Move away from block provider based triggering to network monitor and syncing status from Graph node.
- added a query function that updates the network chainhead hashmap, and returns Subgraph: (network, latest_block) hashmap. (A bit complicated and can probably be refactored in the near future)
- Poll indexingStatuses every 5 seconds from graph node for the above hashmaps
- Match for network and the appropriate examination block, query POI on the examination block
- Removed block providers from the radio, it is still required for `GraphcastAgent` for signing messages and resolve GraphcastID address
Resolves #33

feat: use indexing status to query block info

---

Cargo.toml
src/graphql/mod.rs
src/lib.rs
src/main.rs

- Added logs during attestation process.
- Fixed a bug that is after compare_attestations returns, it cleared all the messages but should be only the ones attested (subgraph and block number specific)
- Allow wait duration configuration `COLLECT_MESSAGE_DURATION` between message_block and attestation block for all networks
- Update wait duration to be time based (seconds) instead of by blocks
- Calculate the comparison trigger - filter by identifier then get the smallest block_number and nonce, add the configured duration.
Resolves #40

feat: env config block duration

---

.github/workflows/docker.yml

This change will enable tagging our Docker image, it will automatically take the release tag and use that. This will greatly help upgradability.

chore: add tag to Docker image

---

Cargo.toml
src/lib.rs
src/main.rs

- In each main loop, info log on network chainhead, number of gossip peers, and number of tracked deployments (topics). At the end of main loop, info log on attestation results (number of checks, success, not found, and the details of divergence)
- indexer id stored and show when attesting
- added network name and deployment hash when printing block info
- Update naming of `message block` to `send message block`, and `compare block` to `compare time`
examples
```
2023-03-15T18:49:03.854408Z  INFO graphcast_sdk::graphql::client_graph_node: Updated latest block pointers for 358 number of subgraphs
2023-03-15T18:48:47.346233Z  INFO poi_radio: Deployment status:
IPFS Hash: QmRDGLp6BHwiH9HAE2NYEE3f7LrKuRqziHBv76trT4etgU
Network: mainnet
Send message block: 16835160
Latest block: 16835174 …
```

refactor: logging improvement

---

Cargo.toml
src/lib.rs
src/main.rs

Instead of using remote stored messages for determining the comparison trigger, use local attestations. 
- updated attestation struct to include timestamp
- For each identifier, find the smallest block and its timestamp for comparison trigger
- After comparing attestation for a certain deployment+block, prune corresponding remote messages and local attestations with equal or earlier block number.
Resolves #70

feat: pruning local+remote after expiry, update collect window to local

---

src/lib.rs
src/main.rs

- Split topic generation into 3 levels as allowed by graphops/graphcast-sdk#150
- Static: only subscribe to user provided topics
- OnChain: Same as before, deployments with an active allocation, querying network subgraph
- Comprehensive: Additional from OnChain, also query Graph node's indexing statuses for the ones with a good index node, i.e. deployment with node not "removed".
- General updates to the SDK
- More precise logging for Operational Summary: include blocks info, complete tracking of non-attested deployments
- Cleaner logging for printing local attestations
Resolves #62 
Resolves #67

topics leveling, stake weight by active status, improve logs

---

Cargo.toml
src/attestation.rs
src/lib.rs
src/main.rs
src/metrics/mod.rs

This PR is an updated version of https://github.com/graphops/poi-radio/pull/75, I've addressed the feedback from it.
Basically just adds two metrics just to pave the way for Prometheus support. 
Will follow up with a PR that adds all the metrics proposed in the original Issue - https://github.com/graphops/graphcast-sdk/issues/51.
[Link to issue](https://github.com/graphops/graphcast-sdk/issues/51)

feat: add basic Prometheus support

---

Cargo.toml
src/attestation.rs
src/lib.rs
src/main.rs

Use `tokio::spawn` for operating send and compare messages in different threads for deployments to improve operation efficiency.
Refactored the main loop for readability.
Resolves #66 
---
Wanted to add [benchmarking](https://github.com/bheisler/criterion.rs) to observe the effects for parallelizing tasks to send and compare messages by deployments, but seems to make more sense to test a single function at a time (by implementing them in a benchmark file) instead of measuring main function directly.

refactor: deployment messages in parallel

---

Cargo.toml
src/attestation/mod.rs
src/lib.rs
src/main.rs
src/server/mod.rs
src/server/model/mod.rs
src/server/observability/mod.rs
src/server/routes/mod.rs

Default to spin up server at `localhost:7700` (refactor in the SDK to provide server-host, server-port)
Available routes
- `/health` for health status
- `/metrics` for http service metrics about the server
- `/api/v1/graphql` for GET and POST requests with playground interface
Example
Basic queries
```
schema {
query: QueryRoot
}
type Attestation {
npoi: String!
stakeWeight: Int!
senders: [String!]!
senderGroupHash: String!
timestamp: [Int!]!
}
type AttestationEntry {
deployment: String!
blockNumber: Int!
attestation: Attestation!
}
type GraphcastMessage {
identifier: String!
payload: RadioPayloadMessage
nonce: Int!
network: String!
blockNumber: Int!
blockHash: String!
signature: String!
}
type QueryRoot {
radioPayloadMessages: [GraphcastMessage!]! …
```

Expose API endpoint

---

poi-radio-grafana.json

Adds a JSON config for the Grafana dashboard with panels that was defined as part of adding initial Prometheus metrics (https://github.com/graphops/poi-radio/pull/91). The config has been generalised.

feat: add Grafana dashboard config

---

pull_request_template.md
src/lib.rs

Modified `active_allocation_hashes` to return an empty vec if the query response (`result.indexer_allocations()`) has errors.  No need for a retry mechanism because `generate_topics` is already being called periodically in `main.rs` (L143):
```rust
if Utc::now().timestamp() % 120 == 0 {
GRAPHCAST_AGENT
.get()
.unwrap()
.update_content_topics(generate_topics().await)
.await;
}
```
https://github.com/graphops/poi-radio/issues/109

fix: return empty vec if indexer_allocations function fails

---

.gitignore
Cargo.toml
e2e-tests.docker-compose.yml
integration-tests/src/main.rs
integration-tests/src/setup/test_radio.rs
integration-tests/src/utils.rs
run-e2e-tests.sh
src/attestation/mod.rs
src/lib.rs
src/main.rs
src/server/mod.rs
src/server/model/mod.rs

- Restructured `ComparisonResult` and refactored the original Enum as `ComparisonResultType` 
- Allow direct query to comparison results, with options to specify the interested deployment and/or block number
- Created a global instance for Radio config
- Refactored `localAttestations` query to optionally take in `deployment` and `block`
Example query
```
{
radioPayloadMessages{
identifier
nonce
blockNumber
network
signature
}
// Optionally provide fields for filter
localAttestations(deployment: "", block: 0){
deployment
blockNumber
attestation{
npoi
}
}
// Optionally provide fields for filter
comparisonResults(deployment: "", block: 0){
deployment
blockNumber
resultType
localAttestation{
npoi
}
attestations{
npoi
}
}
}
```
Resolves #93

Comparison results by graphql query

---

Cargo.lock
Cargo.toml
integration-tests/src/main.rs
integration-tests/src/setup/test_radio.rs
src/config.rs
src/lib.rs
src/main.rs

Moving the Config struct that is responsible for parsing env vars from the command line or env variables away from the SDK and into the Radio. Now the only way to pass these variables into the SDK is through GraphcastAgent::new.
Corresponding SDK PR - https://github.com/graphops/graphcast-sdk/issues/188
https://github.com/graphops/graphcast-sdk/issues/188

refactor: move config parsing to Radio

---

integration-tests/src/main.rs
integration-tests/src/setup/test_radio.rs
src/main.rs

`RADIO_NAME` is now required as a global constant. Alternatively it can be a function that simply returns the name.
hot-fix

fix radio name constant in main

---

Cargo.lock
Cargo.toml
src/main.rs
src/operation.rs

Currently the main event loop of POI radio consist of different types of events that makes sense to execute on different frequencies. Namely there is content topic updates and gossip of the POIs; in the upcoming features, there would be the separation of indexing status updates and gossip of deployment health. We have observed that a particular event may get stuck and block all other operations. 
This PR separate the concerns by adding execution frequencies and event timeouts. Potential next steps are to add a struct to keep all intervals/durations, and to allow user configurations.
Motivated by #115

disable unsubscribe and use timeout

---

src/attestation/mod.rs
src/main.rs
src/server/model/mod.rs

(Repeated PR bc of stupidity with git rebase: https://github.com/graphops/poi-radio/pull/133)
Provide a clear aggregation of the attestations from remote messages with optional filters
```
stakeRatio(filter: {deployment: "__", blockNumber: "___"}){
deployment
blockNumber
compareRatio
}
senderRatio{
deployment
blockNumber
compareRatio
}
```
will provide a string of compare Ratio. 
Examples with sender ratio
- `x/y!/z` where x, y, z are sorted by descending stake weights, and `!` indicates the entry that correspond to the local result. 
- `2/0!` means there are 2 indexers attesting with higher sum of stake weight, and no other indexer has the same nPOI as us.
- `8!` means there are 8 other indexers agreeing with us. 
Improvement for #93

Attestation result ratio str query

---

Cargo.toml
benches/gossips.rs
src/attestation/mod.rs
src/config.rs
src/lib.rs
src/main.rs
src/operation.rs
src/state.rs

To enable the radio to operate seemlessly between sessions, this PR
- adds `PersistedState` struct to track local attestations and remote messages, it should later track comparison result as well.
- adds periodic event to update the persisted state cache.
- allows users to provide a file path that retains the radio state for local attestations and remote messages.
- enables integrations tests to query radio states without going inside of radio operations.
- enables future functional refactoring of radio states
Resolves #113
@test_pls

State persistence

---

.github/workflows/docker.yml
scripts/release.sh

This PR fixes the discrepancy between Docket and git tags, following the official semantic versioning style of `*.*.*`, without a `v` prefix.
1. Updates the release script to remove the "v" prefix
2. Updates the Docker build workflow file to trigger on tags matching `*.*.*` instead of `v*.*.*`
https://github.com/graphops/poi-radio/issues/120

refactor: remove 'v' prefix from release tag
