graphops/poi-radio

.dockerignore, .github/workflows/gen-binaries.yml, .github/workflows/main.yml, Dockerfile, contributing.md, docker-compose.yml
- Adds `Dockerfile` and `docker-compose.yml` files to specify how a Docker image is built and executed (we install and configure everything, then one 1 boot node in the background and 1 light node in the foreground).
- Adds a Github workflow script to build and upload binaries each time a new release is manually created.
=> feat: build binaries and images

Cargo.toml, src/lib.rs, src/main.rs
Use self defined radio definition instead of the pre-defined Graphcast-SDK radio payload definition.
Closes #11
=> feat: self-defined radio definition

.github/workflows/gen-binaries.yml, src/main.rs
This PR fixes the workflow file that builds and uploads the release binaries for Ubuntu and MacOS.
=> refactor: fix release binaries workflow

.github/workflows/docker.yml, src/main.rs
This PR fixes conflicts with the main branch on the SDK and introduces a workflow file to build and upload docker images to Github's container registry.
=> Add workflow to build and upload Docker images

src/lib.rs, src/main.rs
Fix the address being used to query indexer stake when processing messages
Would be nice to have integration test that catches attestation results
=> fix: stake query address

.github/dependabot.yml, Cargo.toml, src/lib.rs, src/main.rs
- Provide waku node key and log level (Minor updates following changes made in SDK https://github.com/graphops/graphcast-sdk/pull/78)
- Add dependabot config
- Fix radio message type name from Ping pong to POI radio
=> feat: waku specific node key and log level

.cargo/config.toml, Cargo.toml
Bump SDK version and add fix for Go compilation issue.
=> chore: bump graphcast-sdk version

Cargo.toml, src/main.rs
after graphops/graphcast-sdk#96 closes
update following graphops/graphcast-sdk#94
=> feat: use environmental variable for pubsub

src/lib.rs, src/main.rs
Changes the comparison trigger logic to be `latest block >= compare block` instead of `latest block == compare block`. Also adds more debug logs.
=> feat: tweak check for comparison trigger

Cargo.toml, src/graphql/mod.rs, src/lib.rs, src/main.rs
Periodically call the update functions (roughly every 120seconds)
Resolves #32
=> periodic topic updates

Cargo.toml, src/lib.rs
=> chore: publish to crates.io

Cargo.toml, Dockerfile, src/lib.rs, src/main.rs
Notifications for POI divergence, both on Slack an Discord.
=> feat: add notifications

pull_request_template.md
Updated the pull request template to add a checklist. I've added this checklist so we can ensure that we're more diligent with our pull requests.
N/A
=> fix: Updated pull request template

README.md
*Add a brief overview of the changes and motivation behind them here*
[Link to issue]()
=> chore: tweak crates badge

Cargo.toml, src/lib.rs
Bug fix on `null` node returned
Fixes #85
=> fix: check for null node

.vscode/settings.json, Cargo.toml, src/attestation.rs, src/lib.rs, src/main.rs, src/metrics/mod.rs
follow up to graphops/graphcast-sdk#177
=> update stake unit conversion in attestation

Dockerfile
This PR helps to reduce image size from 247MB to 52MB
=> refactor: add upx stage to Dockerfile

Dockerfile
Wraps the poi-radio process in [dumb-init](https://github.com/Yelp/dumb-init). See this link for why: https://github.com/Yelp/dumb-init#why-you-need-an-init-system
This may help with #115 if there is a zombie reaping problem
=> feat: add dumb-init to Docker image

Cargo.lock, Cargo.toml, benches/attestations.rs, benches/gossips.rs, src/attestation/mod.rs, src/lib.rs, src/main.rs, src/operation.rs
This PR utilize criterion crate to track the performance of functions. We start off by setting up a few benches to operations that are specific to the POI radio.
Be aware that criterion has the downside of being slower than cargo bench (only available in the nightly build) and experiences small threshold issues for micro-benchmarks.
Micro-benchmarks
- update_block
- update_attestation
- compare_attestations
- comparison_point  
Macro-benchmarks
- gossip_poi: the event loop to set up messages, send messages, and compare messages.
To run the benchmarks, install `cargo-bench` and then run `cargo bench` to see the performances measured across 100 trials
Use `cargo benchcmp` to compare with pervious results such as 
```
cargo bench > before
cargo bench > after
cargo benchcmp before after
``` …
=> refactor: gossip poi refactoring and add benches

.github/workflows/main.yml, README.md
Added an `OR` condition to the CI workflow to trigger tests by leaving a comment to the PR (`@test_pls` 🧎 ). This should allows one to trigger CI tests instead of relying on review approval from others as we currently do.
Also added a few links in README that should help with supporting visitors to the repo
Resolves #137
=> Test trigger and docs

.github/workflows/main.yml
=> chore: revert CI workflow

benches/gossips.rs, src/attestation/mod.rs, src/config.rs, src/lib.rs, src/main.rs, src/metrics/mod.rs, src/operation.rs, src/server/mod.rs, src/server/model/mod.rs, src/state.rs
Follows graphops/graphcast-sdk#218, need to update Cargo.toml after SDK branch merges
=> Configurable logger formats

Cargo.lock, Cargo.toml, benches/gossips.rs, src/attestation/mod.rs, src/config.rs, src/lib.rs, src/main.rs, src/notifier.rs
Adds Telegram divergence notifications, also a small refactor to wrap all notification operations in `Notifier` struct.
https://github.com/graphops/poi-radio/issues/121
=> feat: add telegram notifications

Cargo.lock, poi-radio/Cargo.toml, poi-radio/benches/attestations.rs, poi-radio/src/operator/attestation.rs, poi-radio/src/operator/operation.rs, poi-radio/src/server/mod.rs, poi-radio/src/server/model/mod.rs
Fix the types provided for Http server GraphQL api.
Fixes from #171
=> fix: server context types
